# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCourseDisplay():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_studentLogin(self):
    self.driver.get("https://moodle.org/demo")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(1) span").click()
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "username").send_keys("student")
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.ID, "loginbtn").click()
    assert self.driver.find_element(By.ID, "instance-472-header").text == "Course overview"
    assert self.driver.find_element(By.LINK_TEXT, "Mount Orange School").text == "Mount Orange School"
    self.driver.close()
  
  def test_courseDisplay1(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "All").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by course name").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Card").click()
    self.driver.close()
  
  def test_courseDisplay2(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "All").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by course name").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "List").click()
    self.driver.close()
  
  def test_courseDisplay3(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "All").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by last accessed").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Card").click()
    self.driver.close()
  
  def test_courseDisplay4(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "All").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by last accessed").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "List").click()
    self.driver.close()
  
  def test_courseDisplay5(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "In progress").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by course name").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Card").click()
    self.driver.close()
  
  def test_courseDisplay6(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "In progress").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by course name").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "List").click()
    self.driver.close()
  
  def test_courseDisplay8(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "In progress").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by last accessed").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "List").click()
    self.driver.close()
  
  def test_courseDisplay7(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "In progress").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by last accessed").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Card").click()
    self.driver.close()
  
