# Generated by Selenium IDE

import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCourseDisplay(unittest.TestCase):
  
  def setUp(self):
    self.driver = webdriver.Chrome()
    self.driver.get("https://moodle.org/demo")
    self.login()

  def login(self):
    driver = self.driver
    button_mount_orange_school = driver.find_element(By.LINK_TEXT, "Mount Orange School")
    button_mount_orange_school.click()

    self.assertTrue("Try Moodle in a real-school environment with ready-made accounts" in self.driver.page_source)
    button_login = driver.find_element(By.LINK_TEXT, "Log in")
    button_login.click()

    self.assertTrue("Lost password?" in self.driver.page_source)
    input_username = driver.find_element(By.NAME, "username")
    input_username.clear()
    input_username.send_keys("student")
    input_password = driver.find_element(By.NAME, "password")
    input_password.clear()
    input_password.send_keys("moodle")
    button_handle_login = driver.find_element(By.ID, "loginbtn")
    button_handle_login.click()

    self.assertTrue("Course overview" in self.driver.page_source)

    
  # def test_studentLogin(self):
  #   self.driver.get("https://moodle.org/demo")
  #   self.driver.set_window_size(1221, 753)
  #   self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(1) span").click()
  #   self.driver.find_element(By.LINK_TEXT, "Log in").click()
  #   self.driver.find_element(By.ID, "username").send_keys("student")
  #   self.driver.find_element(By.ID, "password").send_keys("moodle")
  #   self.driver.find_element(By.ID, "loginbtn").click()
  #   assert self.driver.find_element(By.ID, "instance-472-header").text == "Course overview"
  #   assert self.driver.find_element(By.LINK_TEXT, "Mount Orange School").text == "Mount Orange School"
  #   self.driver.close()
  
  def test_courseDisplay1(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "All").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by course name").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Card").click()
    self.driver.close()
  
  def test_courseDisplay2(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "All").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by course name").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "List").click()
    self.driver.close()
  
  def test_courseDisplay3(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "All").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by last accessed").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Card").click()
    self.driver.close()
  
  def test_courseDisplay4(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "All").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by last accessed").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "List").click()
    self.driver.close()
  
  def test_courseDisplay5(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "In progress").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by course name").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Card").click()
    self.driver.close()
  
  def test_courseDisplay6(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "In progress").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by course name").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "List").click()
    self.driver.close()
  
  def test_courseDisplay7(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "In progress").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by last accessed").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "List").click()
    self.driver.close()
  
  def test_courseDisplay8(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, "#groupingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "In progress").click()
    self.driver.find_element(By.CSS_SELECTOR, "#sortingdropdown > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by last accessed").click()
    self.driver.find_element(By.ID, "displaydropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Card").click()
    self.driver.close()
  
  def tearDown(self):
        self.driver.quit()
  
if __name__ == "__main__":
    unittest.main(argv=['first-arg-is-ignored'], exit=False)