# Generated by Selenium IDE

import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditProfile(unittest.TestCase):
  
  def setUp(self):
    self.driver = webdriver.Edge()
    self.driver.get("https://moodle.org/demo")
    self.login()
  
  def login(self):
    driver = self.driver
    button_mount_orange_school = driver.find_element(By.LINK_TEXT, "Mount Orange School")
    button_mount_orange_school.click()

    self.assertTrue("Try Moodle in a real-school environment with ready-made accounts" in self.driver.page_source)
    button_login = driver.find_element(By.LINK_TEXT, "Log in")
    button_login.click()

    self.assertTrue("Lost password?" in self.driver.page_source)
    input_username = driver.find_element(By.NAME, "username")
    input_username.clear()
    input_username.send_keys("student")
    input_password = driver.find_element(By.NAME, "password")
    input_password.clear()
    input_password.send_keys("moodle")
    button_handle_login = driver.find_element(By.ID, "loginbtn")
    button_handle_login.click()

    self.assertTrue("Course overview" in self.driver.page_source)

  def test_editCourse1(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Edit profile").click()
    self.driver.find_element(By.ID, "id_city").send_keys("TPHCM")
    self.driver.find_element(By.ID, "id_country").click()
    dropdown = self.driver.find_element(By.ID, "id_country")
    dropdown.find_element(By.XPATH, "//option[. = 'Viet Nam']").click()
    self.driver.find_element(By.ID, "id_moodlecontainer").click()
    self.driver.find_element(By.ID, "id_submitbutton").click()
    self.driver.close()
  
  def test_editCourse2(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Edit profile").click()
    self.driver.find_element(By.ID, "fitem_id_firstname").click()
    self.driver.find_element(By.ID, "id_firstname").send_keys(".")
    self.driver.find_element(By.ID, "id_moodlecontainer").click()
    self.driver.find_element(By.ID, "fitem_id_lastname").click()
    self.driver.find_element(By.ID, "id_lastname").send_keys(".")
    self.driver.find_element(By.ID, "id_submitbutton").click()
    self.driver.close()
  
  def test_editCourse3(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Edit profile").click()
    self.driver.find_element(By.ID, "id_city").send_keys("SaiGon")
    self.driver.find_element(By.ID, "id_country").click()
    dropdown = self.driver.find_element(By.ID, "id_country")
    dropdown.find_element(By.XPATH, "//option[. = 'Yemen']").click()
    self.driver.find_element(By.ID, "id_cancel").click()
    self.driver.close()
    
  def tearDown(self):
        self.driver.quit()
        
if __name__ == "__main__":
    unittest.main(argv=['first-arg-is-ignored'], exit=False)  
