# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditProfile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_studentLogin(self):
    self.driver.get("https://moodle.org/demo")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(1) span").click()
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "password").send_keys("moodle")
    self.driver.find_element(By.CSS_SELECTOR, ".login-container").click()
    self.driver.close()
  
  def test_editCourse1(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Edit profile").click()
    self.driver.find_element(By.ID, "id_city").send_keys("TPHCM")
    self.driver.find_element(By.ID, "id_country").click()
    dropdown = self.driver.find_element(By.ID, "id_country")
    dropdown.find_element(By.XPATH, "//option[. = 'Viet Nam']").click()
    self.driver.find_element(By.ID, "id_moodlecontainer").click()
    self.driver.find_element(By.ID, "id_submitbutton").click()
    self.driver.close()
  
  def test_editCourse2(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Edit profile").click()
    self.driver.find_element(By.ID, "fitem_id_firstname").click()
    self.driver.find_element(By.ID, "id_firstname").send_keys(".")
    self.driver.find_element(By.ID, "id_moodlecontainer").click()
    self.driver.find_element(By.ID, "fitem_id_lastname").click()
    self.driver.find_element(By.ID, "id_lastname").send_keys(".")
    self.driver.find_element(By.ID, "id_submitbutton").click()
    self.driver.close()
  
  def test_editCourse3(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Edit profile").click()
    self.driver.find_element(By.ID, "id_city").send_keys("SaiGon")
    self.driver.find_element(By.ID, "id_country").click()
    dropdown = self.driver.find_element(By.ID, "id_country")
    dropdown.find_element(By.XPATH, "//option[. = 'Yemen']").click()
    self.driver.find_element(By.ID, "id_cancel").click()
    self.driver.close()
  
