# Generated by Selenium IDE

import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistering(unittest.TestCase):
  
  def setUp(self):
    self.driver = webdriver.Edge()
    self.driver.get("https://moodle.org/demo")
    self.verification()
  
  def verification(self):
    self.driver.get("https://moodle.org/demo")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "password").send_keys("yhLteF.Wq3Uay!X")
    self.driver.find_element(By.CSS_SELECTOR, ".login-signup span").click()
    self.driver.find_element(By.ID, "id_age").click()
    self.driver.find_element(By.ID, "id_age").send_keys("22")
    self.driver.find_element(By.ID, "id_country").click()
    dropdown = self.driver.find_element(By.ID, "id_country")
    dropdown.find_element(By.XPATH, "//option[. = 'Viet Nam']").click()
    self.driver.find_element(By.ID, "id_submitbutton").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.LINK_TEXT, "Next").click()
    self.driver.find_element(By.NAME, "status4").click()
    self.driver.find_element(By.NAME, "status1").click()
    self.driver.find_element(By.NAME, "status2").click()
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.close()
  
  def test_register1(self):
    self.driver.get("https://moodle.org/login/signup.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("userABC123@gmail.com")
    self.driver.find_element(By.ID, "id_email2").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("userABC123@gmail.com")
    self.driver.find_element(By.ID, "id_password").send_keys("@12345678")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_firstname").click()
    self.driver.find_element(By.ID, "id_firstname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_lastname").click()
    self.driver.find_element(By.ID, "id_lastname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_submitbutton").click()
    self.driver.close()
  
  def test_register2(self):
    self.driver.get("https://moodle.org/login/signup.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("userABC123")
    self.driver.find_element(By.ID, "id_email2").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("userABC123")
    self.driver.find_element(By.ID, "id_password").send_keys("@12345678")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_firstname").click()
    self.driver.find_element(By.ID, "id_firstname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_lastname").click()
    self.driver.find_element(By.ID, "id_lastname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_submitbutton").click()
    self.driver.close()
  
  def test_register3(self):
    self.driver.get("https://moodle.org/login/signup.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("userABC123@gmail.com")
    self.driver.find_element(By.ID, "id_email2").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("userABC123@gmail.com")
    self.driver.find_element(By.ID, "id_password").send_keys("@12345678")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_firstname").click()
    self.driver.find_element(By.ID, "id_firstname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_lastname").click()
    self.driver.find_element(By.ID, "id_lastname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_submitbutton").click()
    self.driver.close()
  
  def test_register4(self):
    self.driver.get("https://moodle.org/login/signup.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("userABC123@gmail.com")
    self.driver.find_element(By.ID, "id_email2").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("userABC123@gmail.com")
    self.driver.find_element(By.ID, "id_password").send_keys("@123456")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_firstname").click()
    self.driver.find_element(By.ID, "id_firstname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_lastname").click()
    self.driver.find_element(By.ID, "id_lastname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_submitbutton").click()
    self.driver.close()
  
  def test_register5(self):
    self.driver.get("https://moodle.org/login/signup.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("userABC123@gmail.com")
    self.driver.find_element(By.ID, "id_email2").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("userABC123@gmail.com")
    self.driver.find_element(By.ID, "id_password").send_keys("@1234567")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_firstname").click()
    self.driver.find_element(By.ID, "id_firstname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_lastname").click()
    self.driver.find_element(By.ID, "id_lastname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_submitbutton").click()
    self.driver.close()
  
  def test_register6(self):
    self.driver.get("https://moodle.org/login/signup.php")
    self.driver.set_window_size(1221, 753)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("userABC123@gmail.com")
    self.driver.find_element(By.ID, "id_email2").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("userABC123@gmail.com")
    self.driver.find_element(By.ID, "id_password").send_keys("12345678")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_firstname").click()
    self.driver.find_element(By.ID, "id_firstname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_lastname").click()
    self.driver.find_element(By.ID, "id_lastname").send_keys("loremipsumdominic")
    self.driver.find_element(By.ID, "id_submitbutton").click()
    self.driver.close()
  
  def tearDown(self):
        self.driver.quit()
        
if __name__ == "__main__":
    unittest.main(argv=['first-arg-is-ignored'], exit=False)  
